# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMain.setGeometry(QtCore.QRect(10, 10, 781, 531))
        self.tabMain.setObjectName("tabMain")
        self.tabMainSelectData = QtWidgets.QWidget()
        self.tabMainSelectData.setObjectName("tabMainSelectData")
        self.gbSplitData = QtWidgets.QGroupBox(self.tabMainSelectData)
        self.gbSplitData.setGeometry(QtCore.QRect(20, 90, 591, 151))
        self.gbSplitData.setObjectName("gbSplitData")
        self.lblTrainRatio = QtWidgets.QLabel(self.gbSplitData)
        self.lblTrainRatio.setGeometry(QtCore.QRect(10, 20, 51, 25))
        self.lblTrainRatio.setObjectName("lblTrainRatio")
        self.lblValRatio = QtWidgets.QLabel(self.gbSplitData)
        self.lblValRatio.setGeometry(QtCore.QRect(10, 50, 51, 25))
        self.lblValRatio.setObjectName("lblValRatio")
        self.lblTestRatio = QtWidgets.QLabel(self.gbSplitData)
        self.lblTestRatio.setGeometry(QtCore.QRect(10, 80, 51, 25))
        self.lblTestRatio.setObjectName("lblTestRatio")
        self.chkShuffle = QtWidgets.QCheckBox(self.gbSplitData)
        self.chkShuffle.setGeometry(QtCore.QRect(70, 120, 70, 17))
        self.chkShuffle.setObjectName("chkShuffle")
        self.leDataSetPath = QtWidgets.QLineEdit(self.gbSplitData)
        self.leDataSetPath.setGeometry(QtCore.QRect(210, 20, 361, 25))
        self.leDataSetPath.setObjectName("leDataSetPath")
        self.btnSelectDataSet = QtWidgets.QPushButton(self.gbSplitData)
        self.btnSelectDataSet.setGeometry(QtCore.QRect(210, 50, 361, 25))
        self.btnSelectDataSet.setObjectName("btnSelectDataSet")
        self.lblPath = QtWidgets.QLabel(self.gbSplitData)
        self.lblPath.setGeometry(QtCore.QRect(180, 20, 30, 25))
        self.lblPath.setObjectName("lblPath")
        self.btnSplitDataSet = QtWidgets.QPushButton(self.gbSplitData)
        self.btnSplitDataSet.setGeometry(QtCore.QRect(210, 110, 361, 25))
        self.btnSplitDataSet.setObjectName("btnSplitDataSet")
        self.dsbTrainRatio = QtWidgets.QDoubleSpinBox(self.gbSplitData)
        self.dsbTrainRatio.setGeometry(QtCore.QRect(70, 20, 62, 22))
        self.dsbTrainRatio.setObjectName("dsbTrainRatio")
        self.dsbValRatio = QtWidgets.QDoubleSpinBox(self.gbSplitData)
        self.dsbValRatio.setGeometry(QtCore.QRect(70, 50, 62, 22))
        self.dsbValRatio.setObjectName("dsbValRatio")
        self.dsbTestRatio = QtWidgets.QDoubleSpinBox(self.gbSplitData)
        self.dsbTestRatio.setGeometry(QtCore.QRect(70, 80, 62, 22))
        self.dsbTestRatio.setObjectName("dsbTestRatio")
        self.cbDataType = QtWidgets.QComboBox(self.tabMainSelectData)
        self.cbDataType.setGeometry(QtCore.QRect(120, 30, 241, 22))
        self.cbDataType.setObjectName("cbDataType")
        self.gbSelectPath = QtWidgets.QGroupBox(self.tabMainSelectData)
        self.gbSelectPath.setGeometry(QtCore.QRect(20, 280, 591, 141))
        self.gbSelectPath.setObjectName("gbSelectPath")
        self.btnSelectTrainSet = QtWidgets.QPushButton(self.gbSelectPath)
        self.btnSelectTrainSet.setGeometry(QtCore.QRect(10, 20, 151, 25))
        self.btnSelectTrainSet.setObjectName("btnSelectTrainSet")
        self.btnSelectValSet = QtWidgets.QPushButton(self.gbSelectPath)
        self.btnSelectValSet.setGeometry(QtCore.QRect(10, 60, 151, 25))
        self.btnSelectValSet.setObjectName("btnSelectValSet")
        self.btnSelectTestSet = QtWidgets.QPushButton(self.gbSelectPath)
        self.btnSelectTestSet.setGeometry(QtCore.QRect(10, 100, 151, 25))
        self.btnSelectTestSet.setObjectName("btnSelectTestSet")
        self.lblPath2 = QtWidgets.QLabel(self.gbSelectPath)
        self.lblPath2.setGeometry(QtCore.QRect(180, 20, 30, 25))
        self.lblPath2.setObjectName("lblPath2")
        self.lblPath3 = QtWidgets.QLabel(self.gbSelectPath)
        self.lblPath3.setGeometry(QtCore.QRect(180, 60, 30, 25))
        self.lblPath3.setObjectName("lblPath3")
        self.lblPath4 = QtWidgets.QLabel(self.gbSelectPath)
        self.lblPath4.setGeometry(QtCore.QRect(180, 100, 31, 25))
        self.lblPath4.setObjectName("lblPath4")
        self.leTrainSetPath = QtWidgets.QLineEdit(self.gbSelectPath)
        self.leTrainSetPath.setGeometry(QtCore.QRect(210, 20, 361, 25))
        self.leTrainSetPath.setObjectName("leTrainSetPath")
        self.leValSetPath = QtWidgets.QLineEdit(self.gbSelectPath)
        self.leValSetPath.setGeometry(QtCore.QRect(210, 60, 361, 25))
        self.leValSetPath.setObjectName("leValSetPath")
        self.leTestSetPath = QtWidgets.QLineEdit(self.gbSelectPath)
        self.leTestSetPath.setGeometry(QtCore.QRect(210, 100, 361, 21))
        self.leTestSetPath.setReadOnly(False)
        self.leTestSetPath.setObjectName("leTestSetPath")
        self.lblDataType = QtWidgets.QLabel(self.tabMainSelectData)
        self.lblDataType.setGeometry(QtCore.QRect(20, 30, 91, 25))
        self.lblDataType.setObjectName("lblDataType")
        self.tabMain.addTab(self.tabMainSelectData, "")
        self.tabMainPreprocess = QtWidgets.QWidget()
        self.tabMainPreprocess.setObjectName("tabMainPreprocess")
        self.tabPreprocess = QtWidgets.QTabWidget(self.tabMainPreprocess)
        self.tabPreprocess.setGeometry(QtCore.QRect(20, 10, 731, 461))
        self.tabPreprocess.setTabBarAutoHide(False)
        self.tabPreprocess.setObjectName("tabPreprocess")
        self.tabPreprocessMri = QtWidgets.QWidget()
        self.tabPreprocessMri.setObjectName("tabPreprocessMri")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabPreprocessMri)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 371, 401))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnPreprocessMri = QtWidgets.QPushButton(self.groupBox_3)
        self.btnPreprocessMri.setGeometry(QtCore.QRect(20, 350, 331, 31))
        self.btnPreprocessMri.setObjectName("btnPreprocessMri")
        self.cbPreprocessMriPath = QtWidgets.QComboBox(self.groupBox_3)
        self.cbPreprocessMriPath.setGeometry(QtCore.QRect(140, 20, 211, 22))
        self.cbPreprocessMriPath.setObjectName("cbPreprocessMriPath")
        self.lblPreprocessMriPath = QtWidgets.QLabel(self.groupBox_3)
        self.lblPreprocessMriPath.setGeometry(QtCore.QRect(20, 20, 91, 25))
        self.lblPreprocessMriPath.setObjectName("lblPreprocessMriPath")
        self.cbResampleOption = QtWidgets.QComboBox(self.groupBox_3)
        self.cbResampleOption.setGeometry(QtCore.QRect(140, 60, 211, 22))
        self.cbResampleOption.setObjectName("cbResampleOption")
        self.lblResampleOption = QtWidgets.QLabel(self.groupBox_3)
        self.lblResampleOption.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.lblResampleOption.setObjectName("lblResampleOption")
        self.chkSkullStripping = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkSkullStripping.setGeometry(QtCore.QRect(20, 290, 271, 20))
        self.chkSkullStripping.setObjectName("chkSkullStripping")
        self.chkNormalizationMri = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkNormalizationMri.setGeometry(QtCore.QRect(20, 320, 271, 20))
        self.chkNormalizationMri.setObjectName("chkNormalizationMri")
        self.lblResampleDepth = QtWidgets.QLabel(self.groupBox_3)
        self.lblResampleDepth.setGeometry(QtCore.QRect(20, 240, 91, 16))
        self.lblResampleDepth.setObjectName("lblResampleDepth")
        self.sbResampleDepth = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbResampleDepth.setGeometry(QtCore.QRect(140, 230, 61, 31))
        self.sbResampleDepth.setObjectName("sbResampleDepth")
        self.lblResampleAffine = QtWidgets.QLabel(self.groupBox_3)
        self.lblResampleAffine.setGeometry(QtCore.QRect(20, 120, 91, 16))
        self.lblResampleAffine.setObjectName("lblResampleAffine")
        self.sbResampleRows = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbResampleRows.setGeometry(QtCore.QRect(140, 150, 61, 31))
        self.sbResampleRows.setObjectName("sbResampleRows")
        self.lblResampleCols = QtWidgets.QLabel(self.groupBox_3)
        self.lblResampleCols.setGeometry(QtCore.QRect(20, 200, 91, 16))
        self.lblResampleCols.setObjectName("lblResampleCols")
        self.dsbResampleAffine = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.dsbResampleAffine.setGeometry(QtCore.QRect(140, 110, 62, 31))
        self.dsbResampleAffine.setObjectName("dsbResampleAffine")
        self.sbResampleCols = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbResampleCols.setGeometry(QtCore.QRect(140, 190, 61, 31))
        self.sbResampleCols.setObjectName("sbResampleCols")
        self.lblResampleRows = QtWidgets.QLabel(self.groupBox_3)
        self.lblResampleRows.setGeometry(QtCore.QRect(20, 160, 91, 16))
        self.lblResampleRows.setObjectName("lblResampleRows")
        self.lblVisualizeMri = QtWidgets.QLabel(self.tabPreprocessMri)
        self.lblVisualizeMri.setGeometry(QtCore.QRect(400, 40, 300, 300))
        self.lblVisualizeMri.setStyleSheet("border: 1px solid black")
        self.lblVisualizeMri.setText("")
        self.lblVisualizeMri.setAlignment(QtCore.Qt.AlignCenter)
        self.lblVisualizeMri.setObjectName("lblVisualizeMri")
        self.lblVisualizeMriTitle = QtWidgets.QLabel(self.tabPreprocessMri)
        self.lblVisualizeMriTitle.setGeometry(QtCore.QRect(400, 10, 300, 15))
        self.lblVisualizeMriTitle.setObjectName("lblVisualizeMriTitle")
        self.tabPreprocess.addTab(self.tabPreprocessMri, "")
        self.tabPreprocessFeatureVector = QtWidgets.QWidget()
        self.tabPreprocessFeatureVector.setObjectName("tabPreprocessFeatureVector")
        self.tabPreprocess.addTab(self.tabPreprocessFeatureVector, "")
        self.tabMain.addTab(self.tabMainPreprocess, "")
        self.tabMainNewModel = QtWidgets.QWidget()
        self.tabMainNewModel.setObjectName("tabMainNewModel")
        self.cbModelArch = QtWidgets.QComboBox(self.tabMainNewModel)
        self.cbModelArch.setGeometry(QtCore.QRect(140, 10, 211, 22))
        self.cbModelArch.setObjectName("cbModelArch")
        self.gbModelParameters = QtWidgets.QGroupBox(self.tabMainNewModel)
        self.gbModelParameters.setGeometry(QtCore.QRect(10, 40, 211, 361))
        self.gbModelParameters.setObjectName("gbModelParameters")
        self.lblFilters = QtWidgets.QLabel(self.gbModelParameters)
        self.lblFilters.setGeometry(QtCore.QRect(10, 110, 60, 25))
        self.lblFilters.setObjectName("lblFilters")
        self.lblKernelSize = QtWidgets.QLabel(self.gbModelParameters)
        self.lblKernelSize.setGeometry(QtCore.QRect(10, 140, 60, 25))
        self.lblKernelSize.setObjectName("lblKernelSize")
        self.lblPadding = QtWidgets.QLabel(self.gbModelParameters)
        self.lblPadding.setGeometry(QtCore.QRect(10, 170, 60, 25))
        self.lblPadding.setObjectName("lblPadding")
        self.lblActivation = QtWidgets.QLabel(self.gbModelParameters)
        self.lblActivation.setGeometry(QtCore.QRect(10, 230, 60, 25))
        self.lblActivation.setObjectName("lblActivation")
        self.lblPoolSize = QtWidgets.QLabel(self.gbModelParameters)
        self.lblPoolSize.setGeometry(QtCore.QRect(10, 260, 60, 25))
        self.lblPoolSize.setObjectName("lblPoolSize")
        self.lblDropout = QtWidgets.QLabel(self.gbModelParameters)
        self.lblDropout.setGeometry(QtCore.QRect(10, 290, 60, 25))
        self.lblDropout.setObjectName("lblDropout")
        self.cbPadding = QtWidgets.QComboBox(self.gbModelParameters)
        self.cbPadding.setGeometry(QtCore.QRect(90, 170, 100, 25))
        self.cbPadding.setObjectName("cbPadding")
        self.cbActivation = QtWidgets.QComboBox(self.gbModelParameters)
        self.cbActivation.setGeometry(QtCore.QRect(90, 230, 100, 25))
        self.cbActivation.setObjectName("cbActivation")
        self.sbFilters = QtWidgets.QSpinBox(self.gbModelParameters)
        self.sbFilters.setGeometry(QtCore.QRect(90, 110, 101, 25))
        self.sbFilters.setObjectName("sbFilters")
        self.sbKernelSize = QtWidgets.QSpinBox(self.gbModelParameters)
        self.sbKernelSize.setGeometry(QtCore.QRect(90, 140, 101, 25))
        self.sbKernelSize.setObjectName("sbKernelSize")
        self.sbPoolSize = QtWidgets.QSpinBox(self.gbModelParameters)
        self.sbPoolSize.setGeometry(QtCore.QRect(90, 260, 101, 25))
        self.sbPoolSize.setObjectName("sbPoolSize")
        self.dsbDropout = QtWidgets.QDoubleSpinBox(self.gbModelParameters)
        self.dsbDropout.setGeometry(QtCore.QRect(90, 290, 101, 25))
        self.dsbDropout.setDecimals(2)
        self.dsbDropout.setObjectName("dsbDropout")
        self.lblLstmUnit = QtWidgets.QLabel(self.gbModelParameters)
        self.lblLstmUnit.setGeometry(QtCore.QRect(10, 200, 60, 25))
        self.lblLstmUnit.setObjectName("lblLstmUnit")
        self.sbLstmUnit = QtWidgets.QSpinBox(self.gbModelParameters)
        self.sbLstmUnit.setGeometry(QtCore.QRect(90, 200, 101, 25))
        self.sbLstmUnit.setObjectName("sbLstmUnit")
        self.lblDepth = QtWidgets.QLabel(self.gbModelParameters)
        self.lblDepth.setGeometry(QtCore.QRect(10, 80, 60, 25))
        self.lblDepth.setObjectName("lblDepth")
        self.sbDepth = QtWidgets.QSpinBox(self.gbModelParameters)
        self.sbDepth.setGeometry(QtCore.QRect(90, 80, 101, 25))
        self.sbDepth.setObjectName("sbDepth")
        self.lblCols = QtWidgets.QLabel(self.gbModelParameters)
        self.lblCols.setGeometry(QtCore.QRect(10, 50, 60, 25))
        self.lblCols.setObjectName("lblCols")
        self.sbCols = QtWidgets.QSpinBox(self.gbModelParameters)
        self.sbCols.setGeometry(QtCore.QRect(90, 50, 101, 25))
        self.sbCols.setObjectName("sbCols")
        self.sbRows = QtWidgets.QSpinBox(self.gbModelParameters)
        self.sbRows.setGeometry(QtCore.QRect(90, 20, 101, 25))
        self.sbRows.setObjectName("sbRows")
        self.lblRows = QtWidgets.QLabel(self.gbModelParameters)
        self.lblRows.setGeometry(QtCore.QRect(10, 20, 60, 25))
        self.lblRows.setObjectName("lblRows")
        self.sbClasses = QtWidgets.QSpinBox(self.gbModelParameters)
        self.sbClasses.setGeometry(QtCore.QRect(90, 320, 101, 25))
        self.sbClasses.setObjectName("sbClasses")
        self.lblClasses = QtWidgets.QLabel(self.gbModelParameters)
        self.lblClasses.setGeometry(QtCore.QRect(10, 320, 60, 25))
        self.lblClasses.setObjectName("lblClasses")
        self.lblModelSummary = QtWidgets.QLabel(self.tabMainNewModel)
        self.lblModelSummary.setGeometry(QtCore.QRect(230, 40, 521, 25))
        self.lblModelSummary.setAlignment(QtCore.Qt.AlignCenter)
        self.lblModelSummary.setObjectName("lblModelSummary")
        self.btnCreateModel = QtWidgets.QPushButton(self.tabMainNewModel)
        self.btnCreateModel.setGeometry(QtCore.QRect(230, 320, 521, 25))
        self.btnCreateModel.setObjectName("btnCreateModel")
        self.btnSaveModelParam = QtWidgets.QPushButton(self.tabMainNewModel)
        self.btnSaveModelParam.setGeometry(QtCore.QRect(230, 350, 521, 25))
        self.btnSaveModelParam.setObjectName("btnSaveModelParam")
        self.lblModelArch = QtWidgets.QLabel(self.tabMainNewModel)
        self.lblModelArch.setGeometry(QtCore.QRect(20, 10, 101, 25))
        self.lblModelArch.setObjectName("lblModelArch")
        self.tbModelSummary = QtWidgets.QTextBrowser(self.tabMainNewModel)
        self.tbModelSummary.setGeometry(QtCore.QRect(230, 70, 521, 240))
        self.tbModelSummary.setObjectName("tbModelSummary")
        self.tabMain.addTab(self.tabMainNewModel, "")
        self.tabMainTrain = QtWidgets.QWidget()
        self.tabMainTrain.setObjectName("tabMainTrain")
        self.btnLoadModelParam = QtWidgets.QPushButton(self.tabMainTrain)
        self.btnLoadModelParam.setGeometry(QtCore.QRect(10, 10, 211, 25))
        self.btnLoadModelParam.setObjectName("btnLoadModelParam")
        self.tbModelInfo = QtWidgets.QTextBrowser(self.tabMainTrain)
        self.tbModelInfo.setGeometry(QtCore.QRect(230, 70, 521, 240))
        self.tbModelInfo.setObjectName("tbModelInfo")
        self.lblModelInfo = QtWidgets.QLabel(self.tabMainTrain)
        self.lblModelInfo.setGeometry(QtCore.QRect(230, 40, 521, 25))
        self.lblModelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblModelInfo.setObjectName("lblModelInfo")
        self.gbCompileModel = QtWidgets.QGroupBox(self.tabMainTrain)
        self.gbCompileModel.setGeometry(QtCore.QRect(10, 50, 211, 161))
        self.gbCompileModel.setObjectName("gbCompileModel")
        self.lblOptimizer = QtWidgets.QLabel(self.gbCompileModel)
        self.lblOptimizer.setGeometry(QtCore.QRect(10, 20, 60, 25))
        self.lblOptimizer.setObjectName("lblOptimizer")
        self.cbOptimizer = QtWidgets.QComboBox(self.gbCompileModel)
        self.cbOptimizer.setGeometry(QtCore.QRect(90, 20, 100, 25))
        self.cbOptimizer.setObjectName("cbOptimizer")
        self.cbLoss = QtWidgets.QComboBox(self.gbCompileModel)
        self.cbLoss.setGeometry(QtCore.QRect(90, 50, 100, 25))
        self.cbLoss.setObjectName("cbLoss")
        self.lblLoss = QtWidgets.QLabel(self.gbCompileModel)
        self.lblLoss.setGeometry(QtCore.QRect(10, 50, 60, 25))
        self.lblLoss.setObjectName("lblLoss")
        self.cbMetrics = QtWidgets.QComboBox(self.gbCompileModel)
        self.cbMetrics.setGeometry(QtCore.QRect(90, 80, 100, 25))
        self.cbMetrics.setObjectName("cbMetrics")
        self.lblMetrics = QtWidgets.QLabel(self.gbCompileModel)
        self.lblMetrics.setGeometry(QtCore.QRect(10, 80, 60, 25))
        self.lblMetrics.setObjectName("lblMetrics")
        self.btnCompileModel = QtWidgets.QPushButton(self.gbCompileModel)
        self.btnCompileModel.setGeometry(QtCore.QRect(10, 120, 181, 25))
        self.btnCompileModel.setObjectName("btnCompileModel")
        self.gbFitModel = QtWidgets.QGroupBox(self.tabMainTrain)
        self.gbFitModel.setGeometry(QtCore.QRect(10, 250, 211, 131))
        self.gbFitModel.setObjectName("gbFitModel")
        self.lblBatchSize = QtWidgets.QLabel(self.gbFitModel)
        self.lblBatchSize.setGeometry(QtCore.QRect(10, 20, 60, 25))
        self.lblBatchSize.setObjectName("lblBatchSize")
        self.lblEpoch = QtWidgets.QLabel(self.gbFitModel)
        self.lblEpoch.setGeometry(QtCore.QRect(10, 50, 60, 25))
        self.lblEpoch.setObjectName("lblEpoch")
        self.btnFitModel = QtWidgets.QPushButton(self.gbFitModel)
        self.btnFitModel.setGeometry(QtCore.QRect(10, 90, 181, 25))
        self.btnFitModel.setObjectName("btnFitModel")
        self.sbBatchSize = QtWidgets.QSpinBox(self.gbFitModel)
        self.sbBatchSize.setGeometry(QtCore.QRect(90, 20, 100, 25))
        self.sbBatchSize.setObjectName("sbBatchSize")
        self.sbEpoch = QtWidgets.QSpinBox(self.gbFitModel)
        self.sbEpoch.setGeometry(QtCore.QRect(90, 50, 100, 25))
        self.sbEpoch.setObjectName("sbEpoch")
        self.btnSaveTrainedModel = QtWidgets.QPushButton(self.tabMainTrain)
        self.btnSaveTrainedModel.setGeometry(QtCore.QRect(230, 320, 521, 25))
        self.btnSaveTrainedModel.setObjectName("btnSaveTrainedModel")
        self.btnEncodeTrainLabels = QtWidgets.QPushButton(self.tabMainTrain)
        self.btnEncodeTrainLabels.setGeometry(QtCore.QRect(10, 220, 211, 23))
        self.btnEncodeTrainLabels.setObjectName("btnEncodeTrainLabels")
        self.tabMain.addTab(self.tabMainTrain, "")
        self.tabMainTest = QtWidgets.QWidget()
        self.tabMainTest.setObjectName("tabMainTest")
        self.btnLoadTrainedModel = QtWidgets.QPushButton(self.tabMainTest)
        self.btnLoadTrainedModel.setGeometry(QtCore.QRect(20, 40, 191, 21))
        self.btnLoadTrainedModel.setObjectName("btnLoadTrainedModel")
        self.tbTrainedModelInfo = QtWidgets.QTextBrowser(self.tabMainTest)
        self.tbTrainedModelInfo.setGeometry(QtCore.QRect(230, 40, 521, 240))
        self.tbTrainedModelInfo.setObjectName("tbTrainedModelInfo")
        self.lblTrainedModelInfo = QtWidgets.QLabel(self.tabMainTest)
        self.lblTrainedModelInfo.setGeometry(QtCore.QRect(230, 10, 521, 25))
        self.lblTrainedModelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTrainedModelInfo.setObjectName("lblTrainedModelInfo")
        self.btnPredict = QtWidgets.QPushButton(self.tabMainTest)
        self.btnPredict.setGeometry(QtCore.QRect(20, 110, 191, 25))
        self.btnPredict.setObjectName("btnPredict")
        self.btnLoadEncodeInfo = QtWidgets.QPushButton(self.tabMainTest)
        self.btnLoadEncodeInfo.setGeometry(QtCore.QRect(20, 70, 191, 23))
        self.btnLoadEncodeInfo.setObjectName("btnLoadEncodeInfo")
        self.tbPredictions = QtWidgets.QTextBrowser(self.tabMainTest)
        self.tbPredictions.setGeometry(QtCore.QRect(10, 320, 741, 161))
        self.tbPredictions.setObjectName("tbPredictions")
        self.lblPredictions = QtWidgets.QLabel(self.tabMainTest)
        self.lblPredictions.setGeometry(QtCore.QRect(10, 290, 741, 25))
        self.lblPredictions.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPredictions.setObjectName("lblPredictions")
        self.tabMain.addTab(self.tabMainTest, "")
        self.lblInfo = QtWidgets.QLabel(self.centralwidget)
        self.lblInfo.setGeometry(QtCore.QRect(10, 560, 30, 100))
        self.lblInfo.setObjectName("lblInfo")
        self.teInfo = QtWidgets.QTextEdit(self.centralwidget)
        self.teInfo.setGeometry(QtCore.QRect(40, 560, 750, 100))
        self.teInfo.setObjectName("teInfo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(0)
        self.tabPreprocess.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Deep Learning Tool"))
        self.gbSplitData.setTitle(_translate("MainWindow", "Split Data"))
        self.lblTrainRatio.setText(_translate("MainWindow", "Train:"))
        self.lblValRatio.setText(_translate("MainWindow", "Validation:"))
        self.lblTestRatio.setText(_translate("MainWindow", "Test:"))
        self.chkShuffle.setText(_translate("MainWindow", "Shuffle"))
        self.btnSelectDataSet.setText(_translate("MainWindow", "Browse Data Set"))
        self.lblPath.setText(_translate("MainWindow", "Path:"))
        self.btnSplitDataSet.setText(_translate("MainWindow", "Split"))
        self.gbSelectPath.setTitle(_translate("MainWindow", "Path"))
        self.btnSelectTrainSet.setText(_translate("MainWindow", "Browse Train Set"))
        self.btnSelectValSet.setText(_translate("MainWindow", "Browse Validation Set"))
        self.btnSelectTestSet.setText(_translate("MainWindow", "Browse Test Set"))
        self.lblPath2.setText(_translate("MainWindow", "Path:"))
        self.lblPath3.setText(_translate("MainWindow", "Path:"))
        self.lblPath4.setText(_translate("MainWindow", "Path:"))
        self.lblDataType.setText(_translate("MainWindow", "Data Type:"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabMainSelectData), _translate("MainWindow", "Select Data"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Pre-Process MRI"))
        self.btnPreprocessMri.setText(_translate("MainWindow", "Start"))
        self.lblPreprocessMriPath.setText(_translate("MainWindow", "Path:"))
        self.lblResampleOption.setText(_translate("MainWindow", "Resample Option:"))
        self.chkSkullStripping.setText(_translate("MainWindow", "Deep Brain Skull Stripping by Ivan Itzcovich"))
        self.chkNormalizationMri.setText(_translate("MainWindow", "Z-Score Intensity Normalization by Jacob Reinhold"))
        self.lblResampleDepth.setText(_translate("MainWindow", "Target Depth"))
        self.lblResampleAffine.setText(_translate("MainWindow", "Scale affine:"))
        self.lblResampleCols.setText(_translate("MainWindow", "Target Cols:"))
        self.lblResampleRows.setText(_translate("MainWindow", "Target Rows:"))
        self.lblVisualizeMriTitle.setText(_translate("MainWindow", "Visualizing MRI Volume Slice:"))
        self.tabPreprocess.setTabText(self.tabPreprocess.indexOf(self.tabPreprocessMri), _translate("MainWindow", "MRI"))
        self.tabPreprocess.setTabText(self.tabPreprocess.indexOf(self.tabPreprocessFeatureVector), _translate("MainWindow", "Feature Vector"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabMainPreprocess), _translate("MainWindow", "Pre-Process"))
        self.gbModelParameters.setTitle(_translate("MainWindow", "Model Parameters"))
        self.lblFilters.setText(_translate("MainWindow", "Filters:"))
        self.lblKernelSize.setText(_translate("MainWindow", "Kernel size:"))
        self.lblPadding.setText(_translate("MainWindow", "Padding:"))
        self.lblActivation.setText(_translate("MainWindow", "Activation:"))
        self.lblPoolSize.setText(_translate("MainWindow", "Pool size:"))
        self.lblDropout.setText(_translate("MainWindow", "Dropout:"))
        self.lblLstmUnit.setText(_translate("MainWindow", "LSTM Unit:"))
        self.lblDepth.setText(_translate("MainWindow", "Depth:"))
        self.lblCols.setText(_translate("MainWindow", "Cols:"))
        self.lblRows.setText(_translate("MainWindow", "Rows:"))
        self.lblClasses.setText(_translate("MainWindow", "Classes:"))
        self.lblModelSummary.setText(_translate("MainWindow", "Model Summary"))
        self.btnCreateModel.setText(_translate("MainWindow", "Create Model"))
        self.btnSaveModelParam.setText(_translate("MainWindow", "Save Model Parameters"))
        self.lblModelArch.setText(_translate("MainWindow", "Model Architecture:"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabMainNewModel), _translate("MainWindow", "New Model"))
        self.btnLoadModelParam.setText(_translate("MainWindow", "Load Model Parameters"))
        self.lblModelInfo.setText(_translate("MainWindow", "Info"))
        self.gbCompileModel.setTitle(_translate("MainWindow", "Compile Model"))
        self.lblOptimizer.setText(_translate("MainWindow", "Optimizer:"))
        self.lblLoss.setText(_translate("MainWindow", "Loss:"))
        self.lblMetrics.setText(_translate("MainWindow", "Metrics:"))
        self.btnCompileModel.setText(_translate("MainWindow", "Compile"))
        self.gbFitModel.setTitle(_translate("MainWindow", "Fit Model"))
        self.lblBatchSize.setText(_translate("MainWindow", "Batch Size:"))
        self.lblEpoch.setText(_translate("MainWindow", "Epoch:"))
        self.btnFitModel.setText(_translate("MainWindow", "Fit"))
        self.btnSaveTrainedModel.setText(_translate("MainWindow", "Save Trained Model"))
        self.btnEncodeTrainLabels.setText(_translate("MainWindow", "Encode Train Labels"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabMainTrain), _translate("MainWindow", "Train"))
        self.btnLoadTrainedModel.setText(_translate("MainWindow", "Load Trained Model"))
        self.lblTrainedModelInfo.setText(_translate("MainWindow", "Info"))
        self.btnPredict.setText(_translate("MainWindow", "Predict"))
        self.btnLoadEncodeInfo.setText(_translate("MainWindow", "Load Encode Info"))
        self.lblPredictions.setText(_translate("MainWindow", "Predictions"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabMainTest), _translate("MainWindow", "Test"))
        self.lblInfo.setText(_translate("MainWindow", "Info:"))

